version: '3.8'

services:
  staging:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=staging
    container_name: flask-staging
    restart: unless-stopped

  production:
    build:
      context: .
    ports:
      - "8000:5000"
    environment:
      - APP_ENV=production
    container_name: flask-production
    restart: unless-stopped
